<?php

$dept['1']=array('region'=>'82', 'dept' => 'Ain');
$dept['2']=array('region'=>'22', 'dept' => 'Aisne');
$dept['3']=array('region'=>'83', 'dept' => 'Allier');
$dept['4']=array('region'=>'93', 'dept' => 'Alpes-de-Haute-Provence');
$dept['5']=array('region'=>'93', 'dept' => 'Hautes-Alpes');
$dept['6']=array('region'=>'93', 'dept' => 'Alpes-Maritimes');
$dept['7']=array('region'=>'82', 'dept' => 'Ardèche');
$dept['8']=array('region'=>'21', 'dept' => 'Ardennes');
$dept['9']=array('region'=>'73', 'dept' => 'Ariège');
$dept['10']=array('region'=>'21', 'dept' => 'Aube');
$dept['11']=array('region'=>'91', 'dept' => 'Aude');
$dept['12']=array('region'=>'73', 'dept' => 'Aveyron');
$dept['13']=array('region'=>'93', 'dept' => 'Bouches-du-Rhône');
$dept['14']=array('region'=>'25', 'dept' => 'Calvados');
$dept['15']=array('region'=>'83', 'dept' => 'Cantal');
$dept['16']=array('region'=>'54', 'dept' => 'Charente');
$dept['17']=array('region'=>'54', 'dept' => 'Charente-Maritime');
$dept['18']=array('region'=>'24', 'dept' => 'Cher');
$dept['19']=array('region'=>'74', 'dept' => 'Corrèze');
$dept['2A']=array('region'=>'94', 'dept' => 'Corse-du-Sud');
$dept['2B']=array('region'=>'94', 'dept' => 'Haute-Corse');
$dept['21']=array('region'=>'26', 'dept' => 'Côte-d\'Or');
$dept['22']=array('region'=>'53', 'dept' => 'Côtes-d\'Armor');
$dept['23']=array('region'=>'74', 'dept' => 'Creuse');
$dept['24']=array('region'=>'72', 'dept' => 'Dordogne');
$dept['25']=array('region'=>'43', 'dept' => 'Doubs');
$dept['26']=array('region'=>'82', 'dept' => 'Drôme');
$dept['27']=array('region'=>'23', 'dept' => 'Eure');
$dept['28']=array('region'=>'24', 'dept' => 'Eure-et-Loir');
$dept['29']=array('region'=>'53', 'dept' => 'Finistère');
$dept['30']=array('region'=>'91', 'dept' => 'Gard');
$dept['31']=array('region'=>'73', 'dept' => 'Haute-Garonne');
$dept['32']=array('region'=>'73', 'dept' => 'Gers');
$dept['33']=array('region'=>'72', 'dept' => 'Gironde');
$dept['34']=array('region'=>'91', 'dept' => 'Hérault');
$dept['35']=array('region'=>'53', 'dept' => 'Ille-et-Vilaine');
$dept['36']=array('region'=>'24', 'dept' => 'Indre');
$dept['37']=array('region'=>'24', 'dept' => 'Indre-et-Loire');
$dept['38']=array('region'=>'82', 'dept' => 'Isère');
$dept['39']=array('region'=>'43', 'dept' => 'Jura');
$dept['40']=array('region'=>'72', 'dept' => 'Landes');
$dept['41']=array('region'=>'24', 'dept' => 'Loir-et-Cher');
$dept['42']=array('region'=>'82', 'dept' => 'Loire');
$dept['43']=array('region'=>'83', 'dept' => 'Haute-Loire');
$dept['44']=array('region'=>'52', 'dept' => 'Loire-Atlantique');
$dept['45']=array('region'=>'24', 'dept' => 'Loiret');
$dept['46']=array('region'=>'73', 'dept' => 'Lot');
$dept['47']=array('region'=>'72', 'dept' => 'Lot-et-Garonne');
$dept['48']=array('region'=>'91', 'dept' => 'Lozère');
$dept['49']=array('region'=>'52', 'dept' => 'Maine-et-Loire');
$dept['50']=array('region'=>'25', 'dept' => 'Manche');
$dept['51']=array('region'=>'21', 'dept' => 'Marne');
$dept['52']=array('region'=>'21', 'dept' => 'Haute-Marne');
$dept['53']=array('region'=>'52', 'dept' => 'Mayenne');
$dept['54']=array('region'=>'41', 'dept' => 'Meurthe-et-Moselle');
$dept['55']=array('region'=>'41', 'dept' => 'Meuse');
$dept['56']=array('region'=>'53', 'dept' => 'Morbihan');
$dept['57']=array('region'=>'41', 'dept' => 'Moselle');
$dept['58']=array('region'=>'26', 'dept' => 'Nièvre');
$dept['59']=array('region'=>'31', 'dept' => 'Nord');
$dept['60']=array('region'=>'22', 'dept' => 'Oise');
$dept['61']=array('region'=>'25', 'dept' => 'Orne');
$dept['62']=array('region'=>'31', 'dept' => 'Pas-de-Calais');
$dept['63']=array('region'=>'83', 'dept' => 'Puy-de-Dôme');
$dept['64']=array('region'=>'72', 'dept' => 'Pyrénées-Atlantiques');
$dept['65']=array('region'=>'73', 'dept' => 'Hautes-Pyrénées');
$dept['66']=array('region'=>'91', 'dept' => 'Pyrénées-Orientales');
$dept['67']=array('region'=>'42', 'dept' => 'Bas-Rhin');
$dept['68']=array('region'=>'42', 'dept' => 'Haut-Rhin');
$dept['69']=array('region'=>'82', 'dept' => 'Rhône');
$dept['70']=array('region'=>'43', 'dept' => 'Haute-Saône');
$dept['71']=array('region'=>'26', 'dept' => 'Saône-et-Loire');
$dept['72']=array('region'=>'52', 'dept' => 'Sarthe');
$dept['73']=array('region'=>'82', 'dept' => 'Savoie');
$dept['74']=array('region'=>'82', 'dept' => 'Haute-Savoie');
$dept['75']=array('region'=>'11', 'dept' => 'Paris');
$dept['76']=array('region'=>'23', 'dept' => 'Seine-Maritime');
$dept['77']=array('region'=>'11', 'dept' => 'Seine-et-Marne');
$dept['78']=array('region'=>'11', 'dept' => 'Yvelines');
$dept['79']=array('region'=>'54', 'dept' => 'Deux-Sèvres');
$dept['80']=array('region'=>'22', 'dept' => 'Somme');
$dept['81']=array('region'=>'73', 'dept' => 'Tarn');
$dept['82']=array('region'=>'73', 'dept' => 'Tarn-et-Garonne');
$dept['83']=array('region'=>'93', 'dept' => 'Var');
$dept['84']=array('region'=>'93', 'dept' => 'Vaucluse');
$dept['85']=array('region'=>'52', 'dept' => 'Vendée');
$dept['86']=array('region'=>'54', 'dept' => 'Vienne');
$dept['87']=array('region'=>'74', 'dept' => 'Haute-Vienne');
$dept['88']=array('region'=>'41', 'dept' => 'Vosges');
$dept['89']=array('region'=>'26', 'dept' => 'Yonne');
$dept['90']=array('region'=>'43', 'dept' => 'Territoire de Belfort');
$dept['91']=array('region'=>'11', 'dept' => 'Essonne');
$dept['92']=array('region'=>'11', 'dept' => 'Hauts-de-Seine');
$dept['93']=array('region'=>'11', 'dept' => 'Seine-Saint-Denis');
$dept['94']=array('region'=>'11', 'dept' => 'Val-de-Marne');
$dept['95']=array('region'=>'11', 'dept' => 'Val-d\'Oise');
$dept['971']=array('region'=>'1', 'dept' => 'Guadeloupe');
$dept['972']=array('region'=>'2', 'dept' => 'Martinique');
$dept['973']=array('region'=>'3', 'dept' => 'Guyane');
$dept['974']=array('region'=>'4', 'dept' => 'La Réunion');
$dept['']=array('region'=>'', 'dept' => '');

$regions['1']='Guadeloupe';
$regions['2']='Martinique';
$regions['3']='Guyane';
$regions['4']='La Réunion';
$regions['11']='Île-de-France';
$regions['21']='Champagne-Ardenne';
$regions['22']='Picardie';
$regions['23']='Haute-Normandie';
$regions['24']='Centre';
$regions['25']='Basse-Normandie';
$regions['26']='Bourgogne';
$regions['31']='Nord-Pas-de-Calais';
$regions['41']='Lorraine';
$regions['42']='Alsace';
$regions['43']='Franche-Comté';
$regions['52']='Pays de la Loire';
$regions['53']='Bretagne';
$regions['54']='Poitou-Charentes';
$regions['72']='Aquitaine';
$regions['73']='Midi-Pyrénées';
$regions['74']='Limousin';
$regions['82']='Rhône-Alpes';
$regions['83']='Auvergne';
$regions['91']='Languedoc-Roussillon';
$regions['93']='Provence-Alpes-Côte d\'Azur';
$regions['94']='Corse';
$regions['']='';

?>